### ISSUE TITLE
communication

### ISSUE THREAD

**Issue by nzw0301** [KlisMathClub/linearalgebra#1]
連絡

**Comment by nzw0301** [comment]
第2回の日程調整です．

http://tonton.amaneku.com/list.php?id=20150707075408_HGqLVI

**Comment by nzw0301** [comment]
次回は第1,2章までです

**Comment by nzw0301** [comment]
日付が決定したらここに書いておきます(多分7/17(金)の夜）

**Comment by himkt** [comment]
:+1: 
未だにstudent classの申請結果が返ってきません.

**Comment by nzw0301** [comment]
そんな話もありましたね．．．
弊研究室に1冊あるのでちょこちょこっとメモしたい方はおっしゃってくだされば対応します．

**Comment by nzw0301** [comment]
第2回終わってもstudentclassが間に合わなそうだったら
別方法かんがえたほうがいいかもしれませんね（slackとか）

**Comment by cocuh** [comment]
@all か @KlisMathClub/linearalgebra つかおう

**Comment by nzw0301** [comment]
@KlisMathClub/linearalgebra 

第2回
- 日時 2015/7/21(火)16:00 ~
- 場所 前と同じ

でおねがいします

**Comment by shopetan** [comment]
@nzw0301 
インターンの面接が被ってしまったので第2回は欠席しますm(__)m
すみませんがよろしくお願いします．

**Comment by nzw0301** [comment]
@KlisMathClub/linearalgebra 30分後からでーす

**Comment by nzw0301** [comment]
@KlisMathClub/owners 次回は7月28日16:00~ で第3章です

**Comment by nzw0301** [comment]
@KlisMathClub/linearalgebra 今日ですー

**Comment by nzw0301** [comment]
次の日程調節お願いします
http://tonton.amaneku.com/list.php?id=20150817054152_P35ZhK

**Comment by nzw0301** [comment]
夏休みということで次回は4章から7章までです🍣

**Comment by nzw0301** [comment]
入力お願いしますー

**Comment by nzw0301** [comment]
次回は2015/10/7(水)18:00~でfixします．

**Comment by nzw0301** [comment]
リマインダー
明日です

**Comment by nzw0301** [comment]
次回の日程調節は中間発表が終わったくらいのタイミングでかけます

**Comment by nzw0301** [comment]
次回の日程調節かけます．nzwがたてこんでるので期間が空いて申し訳ありません．．．

8と9章にします
http://tonton.amaneku.com/list.php?id=20151014132046_KyisQM

**Comment by nzw0301** [comment]
↑記入してね

**Comment by nzw0301** [comment]
土曜日かな

**Comment by nzw0301** [comment]
みなさん来れそうな時間帯を考慮したところ明日の12:00~にします．
場所はいつもと同じです．8章と9章を宜しくお願いします．

**Comment by himkt** [comment]
:+1:

**Comment by nzw0301** [comment]
数学勉強会，もう少し演習問題の多いやつで他の本でもやりたい感じはありますね（需要があればですが）

**Comment by nzw0301** [comment]
次回は10章で11月の中旬にやります．
その次は卒論の関係で1月まで一旦中断します．

14章までやってこの線形代数本は終わりにしたいと思います．

**Comment by himkt** [comment]
:+1:

**Comment by nzw0301** [comment]
年内最後のklismathです
http://tonton.amaneku.com/list.php?id=20151106073005_4rDa6v

**Comment by nzw0301** [comment]
おーすっかり忘れてた

10章を明日（土）の13時からにしましょう

**Comment by nzw0301** [comment]
次回年明けの1月に11，12章
2月に13,14章やります

**Comment by nzw0301** [comment]
すみません，1月分の日程調節かけます
11，12章です
http://tonton.amaneku.com/list.php?id=20160112152421_V2K9cD

**Comment by nzw0301** [comment]
とりあえず2016/1/23(土)の13：00〜予定で

**Comment by makky3939** [comment]
登録してませんでしたが参加しますmm

**Comment by nzw0301** [comment]
現在，nzwのプライベートがすごいことになってるのでもしかすると↑から延期するかもしれません．
（分かり次第連絡します，申し訳ありません）

**Comment by nzw0301** [comment]
雪振りそうなので延期しますかね

**Comment by nzw0301** [comment]
あと，@himkt  くんがこれないとのことなので，一応主催したときにメインは2人にあわせるということでしたし，日程変えましょう．（雪も危ないので）

半日前で本当に大変申し訳ありません
