### ISSUE TITLE
わからないこと

### ISSUE THREAD

**Issue by nzw0301** [KlisMathClub/linearalgebra#2]
- わからない問題
- わからない用語

などを書いてください

**Comment by makky3939** [comment]
7章 問1について
今日の解説だと解答例と同じ内容だけだったのですが、
計算過程をもう少し詳しく教えていただきたいです。

**Comment by nzw0301** [comment]
![first](https://cloud.githubusercontent.com/assets/7121753/10345010/8b6c8324-6d61-11e5-8d07-c06d6718f512.jpg)

**Comment by nzw0301** [comment]
![slack for ios upload-3](https://cloud.githubusercontent.com/assets/7121753/10345012/97e43e6c-6d61-11e5-8f1f-79b67019c8b8.jpg)
![slack for ios upload-1](https://cloud.githubusercontent.com/assets/7121753/10345017/9d063666-6d61-11e5-9dd2-b4cc17f8f3b1.jpg)

**Comment by nzw0301** [comment]
要点としては，
ブロック行列(A B; B A)の中身は結局行列なので，行の基本変形と列の基本変形を行えます．
行列Aと行列Bは両方ともn*nの正方行列であるので，AとBの行と列を足すことができます．

というあたりでしょうか．

nzwは字が汚いのと写真なのでわかりにくいかもしれませんが．．．
aとbの真ん中に縦線が入ってるやつはボールド体のつもりです（ベクトルを表すのによく使います）

**Comment by nzw0301** [comment]
↑で不十分でしたら僕のせいなので，次回の時に補足しますね．

**Comment by makky3939** [comment]
ありがとうございます :bow:

**Comment by himkt** [comment]
11章の復習問題の解答が何もかもわからない(T_A(R^3) は(t+2v, t+v+w, v-w)とかいうトンチンカンな値になるしそもそもker(T_A)がない?)のですがどなたか助けてください....

**Comment by hinomn49yk** [comment]
ベクトルx = (x, y, z), (x,y,xは実数)とすると
Ax = (x+2y, x+y+z, y-z)
ここで，v=x+y+z, w=y-zとすると，v+w=x+2y
よって，像=(v+w, v, w)

核は（なぜか）答えが書いてない．
Ax = 0の解が核だから，
Ax = (x+2y, x+y+z, y-z) = (0, 0, 0)
を解くと
核=(-2s, s, s) (sは任意の定数)

**Comment by himkt** [comment]
ありがとうございます。x, y, zをwvで表すのってどうしてですか(本の何ページを見れば良いのか知りたいです)

**Comment by hinomn49yk** [comment]
多分その理由は本には書いてないし私も知らない．．．
答えがシンプルになるからかもしれない

**Comment by himkt** [comment]
なるほど()　ありがとうございます

**Comment by nzw0301** [comment]
p182の定理10.2.1の証明ででてくる手順は「グラム・シュミット直交化」という名前が付いてます．

該当するmastの線形の資料 http://www.chaos.cs.tsukuba.ac.jp/la/lecture/chapter6.pdf

**Comment by nzw0301** [comment]
あかいてあった

**Comment by nzw0301** [comment]
なんとなくslackをつくりました．
