### ISSUE TITLE
正誤表

### ISSUE THREAD

**Issue by nzw0301** [KlisMathClub/linearalgebra#3]
テキストの誤りに気付いたら書きましょう

**Comment by nzw0301** [comment]
p31 解答での行列Sのs11が間違ってました．

正しくは↓かな
![2015-07-10 18 48 00](https://cloud.githubusercontent.com/assets/7121753/8616203/375a2e3a-2734-11e5-858f-65dc5d73564d.png)

**Comment by hinomn49yk** [comment]
例題24.ii) (p.119) の行列式の答えが間違ってました．
正しい答えは -3 ではなく 5 です．

**Comment by makky3939** [comment]
`p89` のいたみ止め `L1`
`1を2に` が `1を4に ` だと思います。

**Comment by hinomn49yk** [comment]
p.154の定理9.2.1（部分空間の定理）
誤：1) ∀x ∈W, ∀y ∈__V__ に対して，x - y∈W
正：1) ∀x ∈W, ∀y ∈__W__ に対して，x - y∈W
だと思われ．

ただ，部分空間で検索しても，
(1) a ∈ W, b ∈ W に対してa + b ∈ W.
このように和で定義しているものしか見当たりませんでした．
とはいえ和でも差でもWの要素同士の計算じゃないとおかしいはずです．

証拠はこれとか
http://www.wakhok.ac.jp/~asami/linalge/pdf/08-9.pdf
http://www.math.nagoya-u.ac.jp/~shinichi/K103.pdf

**Comment by nzw0301** [comment]
初版 p139の回答の2個目の等式，余因子しかかいてないですね．
![2015-10-12 14 53 20](https://cloud.githubusercontent.com/assets/7121753/10422144/14a67248-70f1-11e5-9894-a4486ecb60a1.png)

**Comment by nzw0301** [comment]
@hinomn49yk のやつ，僕も確認してみましたが，誤植だと思います．
以下の本でも正のほうがかいてありますし．（符号は+だけど）

ref http://www.amazon.co.jp/%E7%B7%9A%E5%9E%8B%E4%BB%A3%E6%95%B0%E5%AD%A6-%E6%95%B0%E5%AD%A6%E9%81%B8%E6%9B%B8-1-%E4%BD%90%E6%AD%A6-%E4%B8%80%E9%83%8E/dp/4785313013/ref=sr_1_3?ie=UTF8&qid=1444638338&sr=8-3&keywords=%E7%B7%9A%E5%BD%A2%E4%BB%A3%E6%95%B0%E3%80%80%E4%BD%90%E6%AD%A6

**Comment by himkt** [comment]
p. 8 本質例題2

誤
```
2. 対角線AC, __BC__
```
正
```
2. 対角線AC, __BD__
```

**Comment by nzw0301** [comment]
初版p177の解答
![2015-11-13 17 19 27](https://cloud.githubusercontent.com/assets/7121753/11141657/ba872728-8a2a-11e5-9433-f149534ad729.png)
